name: release
on:
  push:
    tags:
      - "*"

jobs:
  publish-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build example
        run: |
          pip install cookiecutter invoke npm-package-validator
          cookiecutter . --no-input
          cd cookiecutter-webgl
          yarn
          yarn build
          mkdir out
          cp -r dist out/
          cp index.html out/
          touch out/.nojekyll

      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: cookiecutter-webgl/out
          CLEAN: true
